version: '3.8'

services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: express-app
  #   volumes:
  #     - ./app:/usr/src/app
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - mongo
  #     - redis
  #   environment:
  #     MONGO_URI: mongodb://mongo:27017/mydb
  #     REDIS_HOST: redis
  #     REDIS_PORT: 6379

  mongo:
    image: mongo:7
    container_name: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - "8001:8001"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

volumes:
  mongo-data:
